### ISSUE TITLE
Is there any play to add this extension to notion-enhancer?

### ISSUE THREAD

**Issue by peinan** [GorvGoyl/Notion-Boost-browser-extension#1]
Hello, thank you for an awesome extension for notion, and I'm very enjoying this.
I recently learned about [notion-enhancer](https://github.com/dragonwocky/notion-enhancer), a mod loader for notion app that can add many kinds of features made by many people. So I became using notion not on browser but on the native app. I wonder if you could add this wonderful extension to the notion-enhancer.
Thank you.

**Comment by learn2reid** [comment]
+1

**Comment by GorvGoyl** [comment]
AFAIK this browser extension is not compatible for notion-enhancer. You might have better luck reaching out to devs of notion-enhancer since they know it better.
On a side note, I prefer to use Notion in browser (separate window) rather than desktop app because it uses far less CPU resources. In my case desktop app was using ~250% more RAM. For those who don't know Notion desktop app is just a wrapper (another chrome browser) over the Notion website.

**Comment by dragonwocky** [comment]
Hi! I'm the creator of the notion-enhancer. v0.11.0 has been released with massive performance improvements and a whole bunch of new features, including a port to the browser as a Chrome/Firefox extension.

To answer the original question: no. Notion Boost isn't so much a mod that could be included in the enhancer as it is a collection of features, which would all need to be added separately. Using both the Notion Boost and the notion-enhancer browser extensions together wouldn't be recommended either.

However, looking through the Notion Boost feature list, I can see that there are actually a considerable number of overlaps already (a tick indicates that the feature is included in the notion-enhancer):
- [x] Show sticky outline
- [x] Set full width for all pages
- [x] 'Scroll to top' button
- [x] Show full text on hover
- [x] Hide floating help button from all pages
- [x] Hide 'Hidden columns' in board view
- [x] Left align images
- [x] Bolder text in dark mode
- [x] Hide comments section from all pages
- [x] Show code line numbers
- [x] Hide backlinks
- [x] Open full pages instead of preview
- [x] Narrow spacing between list items
- [x] Add indentation lines to lists
- [ ] Close Slash command menu after space
- [ ] Don't show Slash command menu when pressing '/'
- [ ] Enable spellcheck inside code blocks
- [ ] Don't show popup menu when pasting external links
- [ ] Hide notification icon
- [ ] Add more height to page
- [ ] Set small text for all pages
- [ ] Make Rollup URLs clickable

Of the remaining features, I've received numerous requests for the ones related to the '/' menu and do plan to implement them (using entirely my own code). The others I have no plans to implement.

I am also aware that some of the shared features use code copied from the notion-enhancer (definitely open full page & code line numbers, possibly others as well). More up-to-date versions of those features including bug fixes and extra configurations/appearances are available through the notion-enhancer and I'd appreciate it if there was a link somewhere to the notion-enhancer stating as much- according to its license, copying is fine, so long as the original source is attributed. Thanks.

**Comment by dragonwocky** [comment]
Thanks @GorvGoyl
