### ISSUE TITLE
Outline hide/show keyboard shortcut

### ISSUE THREAD

**Issue by DushiRox** [GorvGoyl/Notion-Boost-browser-extension#4]
The ability to hide and show the right sidebar (the outline) with a keyboard shortcut would be fantastic.

**Comment by Luttik** [comment]
I think this is essential since 90% of the premise of Notion is that you can do everything without leaving the keyboard.

**Comment by GorvGoyl** [comment]
Agree. I know the said shortcut should be customizable but I'd like to know your preferred shortcut for this.

**Comment by Luttik** [comment]
If im correct `ctrl+\` is show/hide menu now in notion therefore i think it is logical to show/hide the toc with `ctrl+alt+\`.

Additionally what id like just as much is an focus mode shortcut were you toggle both on/off, for me `ctrl+shift+f11` feels most in line with other tools for that scenario.

**Comment by fcherman** [comment]
While you're in the code, I would appreciate being able to change the width of the pane by dragging, allowing text to wrap as needed.

**Comment by GorvGoyl** [comment]
Binding keyboard is tricky due to extension limitations. I've provided a button to temporarily hide the outline on the current page (until the page refresh)

https://gourav.io/_next/static/media/pages/notion-boost/img/hideoutline.gif

**Comment by FernandoBasso** [comment]
> While you're in the code, I would appreciate being able to change the width of the pane by dragging, allowing text to wrap as needed.

In case dragging proves to be impossible or too difficult (like in the case of the shortcut), somehow provide a way to set its width through an input field, like a preference setting. Not ideal and dynamic as dragging, but would also help nonetheless.

Awesome extension, by the way! Amazing job! 🚀

**Comment by FernandoBasso** [comment]
I see the [v3.0.8 release](https://github.com/GorvGoyl/Notion-Boost-browser-extension/releases/tag/v3.0.8) changed the font size and added wrapping text on the outline to make full heading texts visible. Loved the changes! They make the outline look better and even more useful (I use Notion Booster mainly because of the outline feature). It makes my previous suggestion less relevant; less necessary.

Also, as a Firefox user, I really appreciate the extension has a Firefox version, especially nowadays that Chrome is the fad and people forget it is not the only good browser out there.

Thanks a lot for your work, @GorvGoyl :heart:.

**Comment by GorvGoyl** [comment]
@FernandoBasso Notion Boost is available on Firefox from day 1. https://gourav.io/notion-boost#firefox

**Comment by FernandoBasso** [comment]
> @FernandoBasso Notion Boost is available on Firefox from day 1. https://gourav.io/notion-boost#firefox

Indeed. As I said, “I really appreciate the extension **has** a Firefox version.“ Thanks once more.
